// <auto-generated />
namespace SPD.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_id_agenda_na_pre_consulta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_id_agenda_na_pre_consulta));
        
        string IMigrationMetadata.Id
        {
            get { return "201908020314302_add_id_agenda_na_pre_consulta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
