// <auto-generated />
namespace SPD.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_campo_celular_paciente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_campo_celular_paciente));
        
        string IMigrationMetadata.Id
        {
            get { return "201907261259069_add_campo_celular_paciente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
