// <auto-generated />
namespace SPD.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class drop_column_dump_and_isativoFuncionalidade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(drop_column_dump_and_isativoFuncionalidade));
        
        string IMigrationMetadata.Id
        {
            get { return "201907301804273_drop_column_dump_and_isativoFuncionalidade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
