//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPD.MVC.Geral.Content.Texts
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPD.MVC.Geral.Content.Texts.ErrorResource", typeof(ErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Incapaz de criar a entidade: {0}..
        /// </summary>
        public static string CreateEntityMessage
        {
            get
            {
                return ResourceManager.GetString("CreateEntityMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Incapaz de deletar a entidade: {0}..
        /// </summary>
        public static string DeleteEntityMessage
        {
            get
            {
                return ResourceManager.GetString("DeleteEntityMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Incapaz de editar a entidade: {0}..
        /// </summary>
        public static string EditEntityMessage
        {
            get
            {
                return ResourceManager.GetString("EditEntityMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Para {0}{1}Mensagem de Erro: {2}{3}Mensagem de Exceção: {4}.
        /// </summary>
        public static string ModelStateErrorMessage
        {
            get
            {
                return ResourceManager.GetString("ModelStateErrorMessage", resourceCulture);
            }
        }
    }
}
