//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPD.MVC.PortalWeb.Content.Texts
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FuncionalidadeResource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FuncionalidadeResource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPD.MVC.PortalWeb.Content.Texts.FuncionalidadeResource", typeof(FuncionalidadeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string isAtivo
        {
            get
            {
                return ResourceManager.GetString("isAtivo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preenchimento obrigatório..
        /// </summary>
        public static string isAtivoRequiredMessage
        {
            get
            {
                return ResourceManager.GetString("isAtivoRequiredMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome
        {
            get
            {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Máximo {1} caracteres..
        /// </summary>
        public static string NomeMaxLengthMessage
        {
            get
            {
                return ResourceManager.GetString("NomeMaxLengthMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preenchimento obrigatório..
        /// </summary>
        public static string NomeRequiredMessage
        {
            get
            {
                return ResourceManager.GetString("NomeRequiredMessage", resourceCulture);
            }
        }
    }
}
