//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPD.MVC.PortalWeb.Content.Texts
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPD.MVC.PortalWeb.Content.Texts.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string ActionsLabel
        {
            get
            {
                return ResourceManager.GetString("ActionsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SPD.
        /// </summary>
        public static string ApplicationShortTitle
        {
            get
            {
                return ResourceManager.GetString("ApplicationShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SPD - Sistema Para Dentistas.
        /// </summary>
        public static string ApplicationTitle
        {
            get
            {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string CancelLabel
        {
            get
            {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Todos os direitos reservados.
        /// </summary>
        public static string CopyrightMessage
        {
            get
            {
                return ResourceManager.GetString("CopyrightMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string DeleteLabel
        {
            get
            {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        public static string DetailsLabel
        {
            get
            {
                return ResourceManager.GetString("DetailsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string EditLabel
        {
            get
            {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
    }
}
