//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPD.MVC.PortalWeb.Content.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SessaoUsuarioResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SessaoUsuarioResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPD.MVC.PortalWeb.Content.Texts.SessaoUsuarioResource", typeof(SessaoUsuarioResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data e Hora de Acesso.
        /// </summary>
        public static string DataHoraAcesso {
            get {
                return ResourceManager.GetString("DataHoraAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preenchimento obrigatório..
        /// </summary>
        public static string DataHoraAcessoRequiredMessage {
            get {
                return ResourceManager.GetString("DataHoraAcessoRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço IP.
        /// </summary>
        public static string EnderecoIP {
            get {
                return ResourceManager.GetString("EnderecoIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo {1} caracteres..
        /// </summary>
        public static string EnderecoIPMaxLengthMessage {
            get {
                return ResourceManager.GetString("EnderecoIPMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preenchimento obrigatório..
        /// </summary>
        public static string EnderecoIPRequiredMessage {
            get {
                return ResourceManager.GetString("EnderecoIPRequiredMessage", resourceCulture);
            }
        }
    }
}
