//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPD.MVC.PortalWeb.Content.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UsuarioResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsuarioResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPD.MVC.PortalWeb.Content.Texts.UsuarioResource", typeof(UsuarioResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, preencha um e-mail válido..
        /// </summary>
        public static string EmailEmailAddressMessage {
            get {
                return ResourceManager.GetString("EmailEmailAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo {1} caracteres..
        /// </summary>
        public static string EmailMaxLengthMessage {
            get {
                return ResourceManager.GetString("EmailMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preenchimento obrigatório..
        /// </summary>
        public static string EmailRequiredMessage {
            get {
                return ResourceManager.GetString("EmailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string isAtivo {
            get {
                return ResourceManager.GetString("isAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preenchimento obrigatório..
        /// </summary>
        public static string isAtivoRequiredMessage {
            get {
                return ResourceManager.GetString("isAtivoRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado.
        /// </summary>
        public static string isBloqueado {
            get {
                return ResourceManager.GetString("isBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login deve ter {1} ou menos caracteres..
        /// </summary>
        public static string LoginMaxLengthMessage {
            get {
                return ResourceManager.GetString("LoginMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login deve ter {1} ou mais caracteres..
        /// </summary>
        public static string LoginMinLengthMessage {
            get {
                return ResourceManager.GetString("LoginMinLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preenchimento obrigatório..
        /// </summary>
        public static string LoginRequiredMessage {
            get {
                return ResourceManager.GetString("LoginRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Completo.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo {1} caracteres..
        /// </summary>
        public static string NomeMaxLengthMessage {
            get {
                return ResourceManager.GetString("NomeMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mínimo {1} caracteres..
        /// </summary>
        public static string NomeMinLengthMessage {
            get {
                return ResourceManager.GetString("NomeMinLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo nome é obrigatório..
        /// </summary>
        public static string NomeRequiredMessage {
            get {
                return ResourceManager.GetString("NomeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir Senha.
        /// </summary>
        public static string PasswordConfirmacao {
            get {
                return ResourceManager.GetString("PasswordConfirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas informadas não são iguais..
        /// </summary>
        public static string PasswordConfirmacaoCompareMessage {
            get {
                return ResourceManager.GetString("PasswordConfirmacaoCompareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo {1} caracteres..
        /// </summary>
        public static string PasswordMaxLengthMessage {
            get {
                return ResourceManager.GetString("PasswordMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login deve ter {1} ou mais caracteres..
        /// </summary>
        public static string PasswordMinLengthMessage {
            get {
                return ResourceManager.GetString("PasswordMinLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preenchimento obrigatório..
        /// </summary>
        public static string PasswordRequiredMessage {
            get {
                return ResourceManager.GetString("PasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha informada não atende os critérios de complexidade, comprimento ou histórico do sistema..
        /// </summary>
        public static string PasswordRule1Message {
            get {
                return ResourceManager.GetString("PasswordRule1Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentativas de Login.
        /// </summary>
        public static string TentativasLogin {
            get {
                return ResourceManager.GetString("TentativasLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troca de Senha Obrigatória.
        /// </summary>
        public static string TrocaSenhaObrigatoria {
            get {
                return ResourceManager.GetString("TrocaSenhaObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última Troca de Senha.
        /// </summary>
        public static string UltimaTrocaSenha {
            get {
                return ResourceManager.GetString("UltimaTrocaSenha", resourceCulture);
            }
        }
    }
}
